
const earImages = [
    "/catz/ears/ears-1.png",
    "/catz/ears/ears-2.png",
    "/catz/ears/ears-3.png",
    "/catz/ears/ears-4.png",
    "/catz/ears/ears-5.png",
    "/catz/ears/ears-6.png",
    "/catz/ears/ears-7.png",
    "/catz/ears/ear-tufts-1.png",
    "/catz/ears/ear-tufts-2.png",
    "/catz/ears/ear-tufts-3.png",
    "/catz/ears/ear-tufts-4.png",
    "/catz/ears/ear-tufts-5.png",
    "/catz/ears/ear-tufts-6.png",
    "/catz/ears/ear-tufts-7.png",
    "/catz/ears/ears-down-1.png",
    "/catz/ears/ears-down-2.png",
    "/catz/ears/ears-down-3.png",
    "/catz/ears/ears-down-4.png",
    "/catz/ears/ears-down-5.png",
    "/catz/ears/ears-down-6.png",
    "/catz/ears/ears-down-7.png",
    "/catz/ears/ears-torn-1.png",
    "/catz/ears/ears-torn-2.png",
    "/catz/ears/ears-torn-3.png",
    "/catz/ears/ears-torn-4.png",
    "/catz/ears/ears-torn-5.png",
    "/catz/ears/ears-torn-6.png",
    "/catz/ears/ears-torn-7.png",
]

const bodyMarkings = [
    "/catz/body-markings/spots-1.png",
    "/catz/body-markings/spots-2.png",
    "/catz/body-markings/spots-3.png",
    "/catz/body-markings/spots-4.png",
    "/catz/body-markings/spots-5.png",
    "/catz/body-markings/spots-6.png",
    "/catz/body-markings/spots-7.png",
    "/catz/body-markings/stripes-1.png",
    "/catz/body-markings/stripes-2.png",
    "/catz/body-markings/stripes-3.png",
    "/catz/body-markings/stripes-4.png",
    "/catz/body-markings/stripes-5.png",
    "/catz/body-markings/stripes-6.png",
    "/catz/body-markings/stripes-7.png",
    "/catz/body-markings/swirly-thingies-1.png",
    "/catz/body-markings/swirly-thingies-2.png",
    "/catz/body-markings/swirly-thingies-3.png",
    "/catz/body-markings/swirly-thingies-4.png",
    "/catz/body-markings/swirly-thingies-5.png",
    "/catz/body-markings/swirly-thingies-6.png",
    "/catz/body-markings/swirly-thingies-7.png",
]

const mouths = [
    "/catz/mouths/mouths-1.png",
    "/catz/mouths/mouths-2.png",
    "/catz/mouths/mouths-3.png",
    "/catz/mouths/mouths-4.png",
    "/catz/mouths/mouths-5.png",
    "/catz/mouths/mouths-6.png",
    "/catz/mouths/mouths-7.png",
    "/catz/mouths/mouths-8.png",
]

const eyes = [
    "/catz/eyes/eyes-1.png",
    "/catz/eyes/eyes-2.png",
    "/catz/eyes/eyes-3.png",
    "/catz/eyes/eyes-4.png",
    "/catz/eyes/eyes-5.png",
    "/catz/eyes/eyes-6.png",
    "/catz/eyes/eyes-7.png",
    "/catz/eyes/eyes-8.png",
    "/catz/eyes/eyes-9.png",
]

const colorsOfCat = [
    "/catz/colors-of-cat/colors-of-cat-1.png",
    "/catz/colors-of-cat/colors-of-cat-2.png",
    "/catz/colors-of-cat/colors-of-cat-3.png",
    "/catz/colors-of-cat/colors-of-cat-4.png",
    "/catz/colors-of-cat/colors-of-cat-5.png",
    "/catz/colors-of-cat/colors-of-cat-6.png",
    "/catz/colors-of-cat/colors-of-cat-7.png",
]

  export { earImages, bodyMarkings, eyes, mouths, colorsOfCat }